### PR TITLE
fix poll function in ReadExact

### PR DESCRIPTION
**Pull request by laizy**

### CODE REVIEW

**Comment by cramertj** [comment]
@laizy Good catch! Would you mind adding a test for this as well?

**Comment by cramertj** [comment]
Additionally, could you also add a 0.3 backport? No worries if that's a hassle-- I'll do it otherwise.

**Comment by laizy** [comment]
@cramertj ，have added a test case. But I do not know how to  add 0.3 backport.  😅

**Comment by MajorBreakfast** [comment]
@laizy Yeah "0.3 backport" surprised me as well when I was reading this ^^'

**Pull request merged**
