### PR TITLE
Run rustfmt over codebase

### PR DESCRIPTION
**Pull request by udoprog**
This is one of the few repos I have to disable automatic formatting for.

CC: #917

### CODE REVIEW

**Comment by taiki-e** [comment]
This kills a lot of the work I'm doing. Please wait for at least the crate to stabilize.

**Comment by udoprog** [comment]
These failures seem to be unrelated to the formatting. I can reproduce them locally with `cargo test` on the current master:

```
failures:

---- join_size stdout ----
thread 'join_size' panicked at 'assertion failed: `(left == right)`
  left: `28`,
 right: `32`', futures\tests\async_await_macros.rs:177:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- try_join_size stdout ----
thread 'try_join_size' panicked at 'assertion failed: `(left == right)`
  left: `28`,
 right: `32`', futures\tests\async_await_macros.rs:193:5


failures:
    join_size
    try_join_size
```

**Comment by udoprog** [comment]
> This kills a lot of the work I'm doing. Please wait for at least the crate to stabilize.

FWIW, in principle you should be able to rustfmt your branch as well and then apply your changes `git checkout my-branch .` over the formatted master and have the same result.

**Comment by udoprog** [comment]
Note that the opposite is _not_ true, and I've already lost two patches in progress due to accidentally running `rustfmt` for one reason or another :cry:

**Comment by taiki-e** [comment]
If I remember correctly, it should depend on the type of change.

**Comment by taiki-e** [comment]
By the way, the current setting of rustfmt.toml is different from what we actually use. This is another reason I don't want this PR to be merged now (I personally want to remove rustfmt.toml).

**Comment by taiki-e** [comment]
By the way, if conflicts with editor settings are a problem, I think adding `disable_all_formatting = true` to `rustfmt.toml` is also a good way.

**Comment by cramertj** [comment]
I'd like to hold off on this for the time being.

**Pull request closed without merging**
