### PR TITLE
Only include AtomicWaker with std build

### PR DESCRIPTION
**Pull request by Nemo157**
Workaround for #842 

This is not my preferred solution, but it's the best solution I can think of that works on stable rust

### CODE REVIEW

**Comment by cramertj** [comment]
I'm not sure about this change-- do you know of specific platforms that don't support `AtomicUsize` which you could `cfg` out instead?

**Comment by Nemo157** [comment]
The only platform I know of/care about right now is `thumbv6m-none-eabi`. I assume there are other embedded platforms that don’t, but I can start with just excluding that.

**Comment by Nemo157** [comment]
So, `#[cfg(not(target = "thumbv6m-none-eabi"))]` doesn't seem to be supported (not listed [in the reference](https://doc.rust-lang.org/reference/attributes.html#conditional-compilation) and using it doesn't exclude the code from compiling).

`#[cfg(not(target_arch = "arm"))]` works, but is far too broad since (for example) that includes `armv7-apple-ios` which supports atomic instructions.

As mentioned in the linked ticket `#[cfg(target_has_atomic = "ptr")]` is the correct solution, but that requires the [unstable `cfg_target_has_atomic` feature](https://github.com/rust-lang/rust/issues/32976).

None of the other `cfg` options seem relevant.

**Comment by Nemo157** [comment]
Since #854 introduced a `nightly` feature flags, I've pushed an [alternative branch](https://github.com/rust-lang-nursery/futures-rs/compare/master...Nemo157:target_has_atomic) that uses `#[cfg_attr(feature = "nightly", cfg(target_has_atomic = "ptr"))]` to disable `AtomicWaker` when building with the `nightly` feature for a target that doesn't support it. If you'd prefer that I can replace this PR with it.

**Comment by cramertj** [comment]
@Nemo157 That sounds great to me!

**Comment by Nemo157** [comment]
I have many other things tying me to nightly at the moment, so 🤷‍♂. I’ll wait for #871 to be merged then open a PR to avoid conflicts.

**Pull request closed without merging**
