### PR TITLE
Work on docs and examples for free future functions

### PR DESCRIPTION
**Pull request by Nemo157**

### CODE REVIEW

**Comment by Nemo157** [comment]
(I didn't actually check if the doc links all worked, hopefully Travis can do that for me :smile_cat:)

**Comment by cramertj** [comment]
Travis looks unhappy: https://travis-ci.org/rust-lang-nursery/futures-rs/jobs/409017056#L540

**Comment by Nemo157** [comment]
Fixed, thanks Travis 😄 (also, opened https://github.com/rust-lang/rust/issues/52784 about the extra warnings that didn't break the build but should have).

**Comment by cramertj** [comment]
Great, thanks so much!

**Pull request merged**
