### PR TITLE
Remove TokioDefaultSpawner and tokio-compat

### PR DESCRIPTION
**Pull request by seanmonstar**
These pieces were when `Future` received a `Context` and needed to be able to spawn futures. It no longer does, so these can be removed.

### CODE REVIEW

**Comment by cramertj** [comment]
IMO it's still useful to have an implementation of the `Spawn` trait that is cooperates with the tokio default executor, and I'd be open to keeping this around for that purpose. Is there an argument against keeping this here to be used that way?

**Comment by seanmonstar** [comment]
I dunno, seems like something that would be provided by tokio someday, and it's main reason for existing *in* the futures crate no longer exists...

Is there actual concrete usage where people are using tokio and the `Spawn` trait?

**Comment by cramertj** [comment]
> Is there actual concrete usage where people are using tokio and the Spawn trait?

No idea, but it doesn't seem that weird of a thing to do, e.g. if a 0.3-based crate wanted to be generic over a custom executor, one of which being the tokio executor.

**Comment by seanmonstar** [comment]
It looks like the `Executor01As03` should handle that case (though looks like it's bounds could be loosened to not require `Clone + Send`).

**Comment by cramertj** [comment]
Okay, SGTM! :)

**Pull request merged**
