### PR TITLE
Replace the Future impl for Option with IntoFuture

### PR DESCRIPTION
**Pull request by cramertj**
@alexcrichton

### CODE REVIEW

**Comment by jonhoo** [comment]
Hmm, isn't this a backwards-incompatible change? Specifically:
```rust
let x: Option<impl Future<...>> = ...;
core.run(x)
```
no longer compiles (see https://github.com/jonhoo/fantoccini/issues/8).

**Comment by jonhoo** [comment]
And as far as I can tell, there isn't a forwards-compatible way to change this either, since `Option<F>` doesn't implement `IntoFuture` in `0.1.18` :/

**Comment by luser** [comment]
This change broke people doing `cargo install sccache` because cargo doesn't respect Cargo.lock in that case.

**Comment by cramertj** [comment]
Yes, this change was backwards-incompatible and was only supposed to appear in the 0.2 release.

**Comment by cramertj** [comment]
I've opened https://github.com/rust-lang-nursery/futures-rs/pull/914 with the revert and yanked 0.1.19.

**Pull request merged**
