### PR TITLE
Spawn 0.1 futures when using them as 0.3 futures

### PR DESCRIPTION
**Pull request by cramertj**
This eliminates the need for separate configuration of a global task
when using 0.1 futures on an 0.3 executor.

Fixes https://github.com/rust-lang-nursery/futures-rs/issues/1251

### CODE REVIEW

**Comment by cramertj** [comment]
Needs https://github.com/rust-lang-nursery/futures-rs/pull/1281 to avoid regressing `AsyncRead`/`AsyncWrite` support.

**Comment by seanmonstar** [comment]
I believe this will make intermediate futures that go through `compat` much more expensive, even though they don't actually need their own task allocated.

**Comment by seanmonstar** [comment]
I'm thinking it'd be better to modify futures 0.1 to allow a `with_notify` that doesn't need a task previously set.

**Comment by Nemo157** [comment]
I also wonder what this means for when you're using a 0.1 executor, running some 0.3 async functions and terminating in 0.1 leaf I/O (the common case for the compat layers I assume). The 0.3 async functions -> 0.1 leaf I/O boundary will allocate a new `Spawn` separate from the one that the executor is running the task under. Wake notifications should flow back from the 0.1 leaf I/O notify ->  0.3 waker -> 0.1 executor notify, but I don't have enough familiarity with 0.1 internals to know whether the `Spawn` instance can include other "global" state that may need to be synchronized between the executor and leaf I/O.

**Comment by cramertj** [comment]
> I'm thinking it'd be better to modify futures 0.1 to allow a with_notify that doesn't need a task previously set.

That wouldn't allow task-local data.

Why do you think this is much more expensive?

**Comment by seanmonstar** [comment]
> That wouldn't allow task-local data.

I'm pretty sure task-local data won't survive this either. If you've gone through the compat layer once, a task-local key from higher up won't be visible in this `Spawn`'s map.

**Comment by cramertj** [comment]
A task-local key from higher up will not, that is true-- this encapsulates task-local data, which I believe is the only sensible behavior when looking to run an 0.1 future on an 0.3 executor.

**Comment by seanmonstar** [comment]
I re-read through the source of `Spawn`, and it seems I assumed it automatically boxed the future. I was worried about introducing dynamic dispatch when intermediate futures could probably just be inline.

**Comment by cramertj** [comment]
@seanmonstar Gotcha! Yeah, that would be unfortunate. How do you feel about this PR now? Would you still prefer a different approach, or do you think this works?

**Comment by cramertj** [comment]
@seanmonstar Makes sense-- thanks for the review!

**Pull request merged**
