### PR TITLE
Stage 0.2 Release

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by Nemo157** [comment]
Should `futures-stable` be removed from the facade as well (it appears building with the `nightly` feature is broken because it's attempted to be facaded but not actually enabled)?

**Comment by cramertj** [comment]
@Nemo157 Ah, I was just a flag too overzealous when removing the nightly features deps. I'll add back the dependency (building w/ nightly fails CI right now anyways because of breaking changes to the proc macro api).

**Comment by Nemo157** [comment]
Damn, I was sort of hoping that `StableFuture` was not going to be published in 0.2 yet. I'm just about to propose a breaking change to how it relates to `Future` to hopefully make it more ergonomic to use.

**Comment by cramertj** [comment]
@Nemo157 yeah, I think it's fine for us to make breaking changes to something like `StableFuture` (which is only usable on nightly and doesn't currently have much of a point without async/await).

**Comment by Nemo157** [comment]
> doesn't currently have much of a point without async/await

Not entirely no point, I have 4 or 5 manual implementations (2 for supporting DMA and a few basic adaptors that can't be written via async/await).

**Comment by cramertj** [comment]
No, not entirely :)

**Comment by jimmycuadra** [comment]
What was the context of this? I had async/await working using futures master from a couple days ago, but it doesn't work now with the real 0.2.0 release. PRs with no description make me sad. :{

**Comment by cramertj** [comment]
@jimmycuadra An API change to proc macros on nightly broke the async/await macros, so they were removed prior to the release. There will be another release next week with them added back.

**Pull request merged**
