### PR TITLE
Drop support for non-immovable #[async] macros

### LINKED ISSUE #918: Name consistency of async function attributes
Attributes of `async` and `async_stream` to box them which are currently named `pinned` and `pinned_send` should be the same as `async_move` and `async_stream_move` like `boxed` and `boxed_send` from users' aspects. That is because `async` or `async_stream` functions are pinned anyway whether they are boxed or not.

### PR DESCRIPTION
**Pull request by Nemo157**
Fixes #918
Subsumes #936

### CODE REVIEW

**Comment by raviqqe** [comment]
Personally, I like your naming of `unpin`. But, can `boxed` be `box` instead as `unpin` sounds like a verb?

**Comment by withoutboats** [comment]
How do you feel about removing the `unpin`/`async_move` feature entirely? It seems like it requires duplicating literally every API - including `await` - and the current version of the RFC for built-in syntax doesn't support this at all.

**Comment by Nemo157** [comment]
I'm :+1: for that, I'm only using immovable futures personally. If the wider futures community is planning on skipping 0.2 for 0.3 (which has been my impression of at least tokio and hyper) I think there's less need to try and provide a compatible macro for experimenting with. I don't want to make that call though, since I'm working with quite a niche usage of futures at the moment. If you/someone makes the call I can update this PR to remove it.

**Comment by withoutboats** [comment]
delete it! :tada:

**Comment by withoutboats** [comment]
LGTM, will merge after the tests run

**Pull request merged**
