### PR TITLE
Rename `Sink::SinkError` to `Sink::Error`

### LINKED ISSUE #1707: Rename Sink::SinkError to just Sink::Error
It was originally made `SinkError` so that implementations that required a generic to be both `Stream` and `Sink` could more easily distinguish error types. However, it's possible to disambiguate using `<S as Sink<Item>>::Error` in an impl (and even temporary generics can be used), and it otherwise reads as a stutter.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #1707

### CODE REVIEW

**Comment by cramertj** [comment]
r=me with travis passing.

**Comment by seanmonstar** [comment]
Hrm, I'm guessing this failure is due to improvements in nightly?

```
---- join_size stdout ----
thread 'join_size' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `44`', futures/tests/async_await_macros.rs:178:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by taiki-e** [comment]
@seanmonstar Yes, that is because the generator size has been improved. (https://github.com/rust-lang/rust/pull/61922).

**Comment by cramertj** [comment]
Yeah, I've got a PR updating those.

**Comment by cramertj** [comment]
https://github.com/rust-lang-nursery/futures-rs/pull/1711

**Comment by cramertj** [comment]
@seanmonstar Would you mind rebasing just so I can see a clean CI run on this before merging?

**Pull request merged**
