### PR TITLE
Use a Vec for Shared waiters to reduce memory usage.

### PR DESCRIPTION
**Pull request by stuhood**
As discovered in https://github.com/pantsbuild/pants/issues/5990, the minimum allocation of the `waiters` `HashMap` in `future::Shared` is ~3kb. In discussions in the tokio gitter room, @tanriol pointed out that the minimum capacity of a `HashMap` is 32 entries, and the key and value in the waiters map add up to 80 bytes.

Our application creates a DAG of `future::Shared` instances, with an average dependency count per graph node of about 2. For a large usecase in that context, I saw:
```
futures 0.1.21:
  cpu:  5:06.17
  wall: 4m32.984s
  mem:  3495M

this patch:
  cpu:  5:06.19
  wall: 4m27.861s
  mem:  2759M
```
So: effectively no CPU usage difference, but a 21% memory savings.

### CODE REVIEW

**Comment by tanriol** [comment]
Not sure whether keeping the vector sorted is worth it, especially for very short vectors.

For long vectors, insertion will normally be almost-at-the-end (waiter IDs are increasing, but a clone created later can be polled and inserted earlier). Deletion depends on the usage pattern -- if most clones are long-lived except for a few, it will be almost-at-the-end too, but not if all the clones have approximately the same max age. So looks like a sorted vector may be better after all, but not sure.

**Comment by cramertj** [comment]
I use a slab (https://github.com/carllerche/slab) for this in my own applications, and I'd suggest doing that here. It's a vec with a built-in free list.

**Comment by stuhood** [comment]
@cramertj : I might not be understanding, but to use `Slab`, we'd need to have somewhere to store the keys, right? Is the idea that we would have a `Vec<usize>` containing the slab keys, and a static `Slab` of the waiters?

**Comment by stuhood** [comment]
> a static `Slab` of the waiters

Although that would introduce a `Mutex` here I think? @cramertj : Is that what you had in mind?

**Comment by cramertj** [comment]
@stuhood `Mutex<Slab<Task>>` would go exactly where the current `Mutex<HashMap<usize, Task>>` is.

**Comment by stuhood** [comment]
@cramertj : Ah, ok.

I thought that you were suggesting that many `Shared` instances would use the same `Slab`, which would likely be very efficient in terms of allocation, but potentially bottlenecked on synchronization.

**Comment by cramertj** [comment]
I've done a refactor of Shared for 0.3 that also includes the change to use `Slab`-- feel free to take a look and backport what you like 0.1: https://github.com/rust-lang-nursery/futures-rs/pull/1047/commits/8632fc0390f90aa96a1324ce4829ad58828d8db8

**Comment by stuhood** [comment]
@cramertj : We ended up switching away from `Shared` for our usecase for other reasons, so we don't need a backport. I'll close this for now.

Thanks!

**Pull request closed without merging**
