### PR TITLE
Add extension traits for io 0.1 -> 0.3 compat

### PR DESCRIPTION
**Pull request by Nemo157**

### CODE REVIEW

**Comment by cramertj** [comment]
Looks like the travis failure is an ICE, ick: https://travis-ci.com/rust-lang-nursery/futures-rs/jobs/182570651#L609

**Comment by cramertj** [comment]
Would you mind adding a test or a doctest showing a successful usage of this? LGTM otherwise, thanks!

**Comment by Nemo157** [comment]
Doc tests for these and other compat methods added. The ICE is rust-lang/rust#58888 so should be fixed as soon as bors gets around to merging PRs again.

**Comment by Nemo157** [comment]
And CI is passing again 😁

**Comment by cramertj** [comment]
Nice! :)

**Pull request merged**
