### PR TITLE
2018-08-18 toykio -> fahrenheit renaming

### PR DESCRIPTION
**Pull request by polachok**
Please delete this post, it creates too much confusion in the community, e.g.:

https://github.com/polachok/fahrenheit/issues/3
https://www.reddit.com/r/rust/comments/97zzig/toykio_and_futures_03/

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
I think this blog post is good work and we should talk this through first. We all invested a lot of time into writing/reviewing it and we're happy with the result. @aturon and all the reviewers of the post (me, @cramertj and @Nemo157) were all well aware of the name. I still think that it is a clever pun.

My suggestion is: Add the hyphen. `toy-kio` looks visually different than `tokio`, we still get the pun and the separation of the word "toy" makes it clear that it's not "Tokio".

(BTW Tokyo (the city) is spelled "Tokio" in German 😅)

**Comment by polachok** [comment]
I renamed the project to fahrenheit already and yanked it from crates, so we can do s/toykio/fahrenheit/ if you're absolutely against removal of the post.

**Comment by MajorBreakfast** [comment]
A lot of work went into this post (especially from your side) and I don't want that it was for nothing. I've contacted @aturon and I want to hear his and also the feedback of the others before I click a button to remove a post which we all like.

**Comment by aturon** [comment]
Yes we should definitely keep the post up, but renaming sounds good to me. Sorry about the poor response on that front :(

**Comment by MajorBreakfast** [comment]
Alright. "fahrenheit" it is 🙂

**Pull request merged**
