### PR TITLE
Lib.rs Example and Async Block Callout (#1203)

### PR DESCRIPTION
**Pull request by dbcfd**
Not ready for merge.

This example is meant to address #1203 providing clarification of how context is created and passed through macros and the async keyword.

The code in examples folder is currently meant to be temporary (quick compilation of single example), and to be removed when example is finalized.

Re-open from https://github.com/rust-lang-nursery/futures-rs/pull/1220

### CODE REVIEW

**Comment by dbcfd** [comment]
@MajorBreakfast Another pass at the docs, cleaned up code per your suggestions.

**Comment by cramertj** [comment]
> Not ready for merge.

@dbcfd are there more changes you want to make to this? Are you interested in getting it updated and landed?

**Comment by dbcfd** [comment]
@cramertj Was waiting on feedback, but if it seems useful, can rebase it and prepare it for merge.

**Comment by cramertj** [comment]
It seems useful to me! Thanks

**Comment by dbcfd** [comment]
@cramertj Updated based on changes to the crate (e.g. spawn! removal). The examples are now full examples and referenced in the workspace.

**Comment by cramertj** [comment]
Looks like there are some test failures

**Comment by dbcfd** [comment]
@cramertj Noticed in fixing those that minimum version is still 1.36. Is that going to move to 1.39, or should I flag this behind async-await feature?

**Comment by cramertj** [comment]
I don't have much of a preference either way-- despite what CI says, the README only promises compatibility with 1.39 and later, so I have no objections to changing CI.

**Comment by taiki-e** [comment]
> I don't have much of a preference either way-- despite what CI says, the README only promises compatibility with 1.39 and later, so I have no objections to changing CI.

FYI: filed #1966 to fix ci issue.

**Comment by dbcfd** [comment]
@cramertj Can you review this again, I added the examples to the Cargo.toml, and fixed things up against latest master.

**Comment by cramertj** [comment]
Looks reasonable to me! thanks!

**Pull request merged**
