### PR TITLE
Fix `AtomicWaker`

### PR DESCRIPTION
**Pull request by carllerche**
The previous attempt at fixing `AtomicWaker` ended up introducing new
bugs. This is partially due to the implementation evolving (incorrectly)
over time.

This patch provides a brand new, from scratch, implementation of
`AtomicWaker`, addressing the soundness issues.

### CODE REVIEW

**Comment by aturon** [comment]
Once this lands, we should put out a `-beta`.

**Comment by cramertj** [comment]
LGTM-- will merge w/ CI

**Comment by aturon** [comment]
Merged! @cramertj want to put out a -beta?

**Comment by cramertj** [comment]
@aturon Sure!

**Pull request merged**
