### PR TITLE
compat: use a CurrentRef waker in 01 compat

### PR DESCRIPTION
**Pull request by seanmonstar**
Just to poll a `Future01`, it isn't yet necessary to call
`task01::current()`, nor store it in an `Arc::new`. All that is needed
is a "reference", and if someone calls `waker().clone()`, *then* we can
do the allocations.

### CODE REVIEW

**Comment by seanmonstar** [comment]
CI failure seems unrelated to this PR.

**Comment by Nemo157** [comment]
CI is definitely unrelated, doc failure is the buggy rustdoc link detection (which I will open a pr to disable soon) and benchmarks are caused by https://github.com/rust-lang/rust/pull/54116, left a comment there to try and sort that out.

**Comment by seanmonstar** [comment]
I've tried restarting those CI jobs, but they still fail. Seems this can't be merged with them failing...

**Comment by Nemo157** [comment]
Admins can merge even with failing ci (and as far as I know only the admins have merge rights here anyway).

**Comment by aturon** [comment]
Merged, sorry for the delay (and feel free to ping if things are getting stuck.)

**Pull request merged**
