### PR TITLE
Don't close sinks in send_all/forward

### LINKED ISSUE #462: Can sink be reused after `send_all`?
Hi, I notice that `SendAll` struct will call `close` method when polling, doesn't it mean that though `SendAll` will be resolved back to Sink eventually, but it can't be reused anymore? And I don't find any combinator except `SendAll` will call close under the hook. So if I want to close a sink asynchronously, do I have to either reimplement a Future or just use `SendAll`?

### PR DESCRIPTION
**Pull request by alexcrichton**
Closes #462
Closes #485

### CODE REVIEW

**Comment by cramertj** [comment]
:shipit:

**Comment by Ekleog** [comment]
Hmm, would it make sense to backport to 0.1? tokio uses 0.1, and so is stuck with this issue :/

**Comment by cramertj** [comment]
@Ekleog Unfortunately this is a breaking change, and so is only available with futures 0.2.

**Comment by Ekleog** [comment]
Oh :/ well, so be it, then, thanks!

**Pull request merged**
