### PR TITLE
Change Wake trait to take an Arc (now std-only)

### PR DESCRIPTION
**Pull request by cramertj**
Continuation of #811

cc @carllerche

### CODE REVIEW

**Comment by carllerche** [comment]
If this works, seems good to me. I personally have never used `Wake` and have always favored the unsafe version. Maybe this will help make the safe one more useful.

**Comment by alexcrichton** [comment]
r=me, but looks like CI is failing?

**Comment by aturon** [comment]
:+1:

**Comment by leodasvacas** [comment]
I thought `impl<T: Wake> From<&'static T> for Waker` was cute but I guess nobody used it.

**Pull request merged**
