### PR TITLE
Change FutureObj to use a `*mut dyn Future` fat pointer

### PR DESCRIPTION
**Pull request by Nemo157**
r? @cramertj

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@Nemo157 looks like this has a merge conflict.

**Comment by Nemo157** [comment]
Conflict is probably just around the `feature` changes, I'll fix it soon. But this is also blocked on a new nightly being released with https://github.com/rust-lang/rust/pull/60165 included.

**Comment by cramertj** [comment]
@Nemo157 `Pin` is `repr(transparent)`, so it'd be sound to add those conversions in an `unsafe` manner to futures-rs. I'd personally prefer to do that now rather than to take a dependency on a new unstable API.

**Comment by Nemo157** [comment]
👍 sure, I'll push an update switching back to doing the conversion manually.

**Pull request merged**
