### PR TITLE
Remove unnecessary locals in join! macros

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
Doesn't that remove support for `!Unpin` futures?

**Comment by MajorBreakfast** [comment]
Ah no I see. You poll a reference.

**Comment by cramertj** [comment]
@MajorBreakfast lol, good catch-- meant to use `new_unchecked`. This is safe because we're moving the future into a local that isn't accessible by the end user.

**Comment by MajorBreakfast** [comment]
Hehe ^^' I shouldn't have posted the second comment.

Maybe also add a comment to the `let` "Move future into local"

**Comment by cramertj** [comment]
I've added some tests to ensure that we continue to allow `!Unpin` futures.

**Pull request merged**
