### PR TITLE
Reexport future::Option

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by aturon** [comment]
I feel queasy about the name clash with `std` but that's a separate concern from this PR.

r+ after rebase

**Comment by cramertj** [comment]
@aturon we do the same thing for `future::Result`, which is actually `future::FutureResult` in `0.1` but was changed in the transition to `0.2`. Do you have a preferred naming scheme?

**Comment by aturon** [comment]
I generally disprefer shadowing names from `std`, especially ones that are in the prelude. `FutureResult` and `FutureOption` seem good to me...

**Comment by cramertj** [comment]
Haha. The reasoning for the name change is that (I think) most people `use futures::future;` and then refer to the types like `future::Result`, in which case `future::FutureResult` causes stuttering.

**Comment by aturon** [comment]
yeah that's usually how this kind of thing goes. I've personally come to prefer the stuttering to the confusion that can otherwise arise -- but only for prelude-level types.

**Comment by carllerche** [comment]
I personally rarely (if ever?) refer to future types scoped by the module. Only the free fns.

**Comment by cramertj** [comment]
Okay! i'll send a PR to change both.

**Comment by cramertj** [comment]
see https://github.com/rust-lang-nursery/futures-rs/pull/807

**Pull request merged**
