### PR TITLE
Add FuturesUnordered::next_some

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by Nemo157** [comment]
Having `FusedFuture::is_terminated()` transition from `true` -> `false` seems surprising to me.

It seems like this could be provided as `StreamExt::next_some where Self: FusedStream`, then the question would be whether it’s appropriate to implement `FusedStream` for `FuturesUnordered` delegating to `is_empty` (I guess it’s about as appropriate as having it return `None` while empty, surprising but necessary for some use cases).

My other thought based on the example would be to use a channel abstraction instead of a collection so that you know once all senders have been dropped (with `buffer_unordered` to get the same concurrency). I assume that’s not wanted for performance reasons, could bringing back `futures::channel::unsync::mpsc` provide enough performance? (although, then you lose `Send` as well...)

**Comment by Nemo157** [comment]
Only other thought I had on name is `next_unwrap`/`next_expect` since that’s what it’s doing other than the fusing. I think that’s probably worse than the current name though.

**Comment by alexcrichton** [comment]
Ah I think I'm far enough out of the loop to not be much help on naming bikesheds :(

**Comment by cramertj** [comment]
@Nemo157 
> FusedStream does not guarantee that is_terminated() will return true before Stream::poll_next returns None

Yes, this is intentional. It returns `is_terminated()` *after* `Stream::poll_next` returns `None`.

**Comment by cramertj** [comment]
Superseded by #1329

**Pull request closed without merging**
