### PR TITLE
Update for latest nightly changes to rename Pin to PinMut

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/rust-lang-nursery/futures-rs/issues/1002

### CODE REVIEW

**Comment by sdroege** [comment]
The remaining failure requires adding `#![feature(extern_prelude)]` to the futures and futures-channel crates. But futures-channel does not even have a nightly feature right now. What to do about this?

**Comment by Nemo157** [comment]
It's very annoying that it doesn't say where is trying to access a crate through the prelude. Since it's only happening while building the docs I'm guessing it's related to some link attempting to resolve through an extern crate.

Checking the [last successful build shows](https://travis-ci.org/rust-lang-nursery/futures-rs/jobs/373242465#L522): 

```
warning: [futures_core::Stream] cannot be resolved, ignoring it...
```

which is probably [this line](https://github.com/rust-lang-nursery/futures-rs/blob/62827f1776e833a948cb81582988cb7a70a8b700/futures-channel/src/mpsc/mod.rs#L6).

This should be fixable by changing it to one of ``[`Stream`]``, ``[`Stream`](Stream)`` or ``[`Stream`](::futures_core::Stream)``.

The futures crate appears to have a lot of similar issues, judging by the warnings in the linked build.

I think this is worth opening an issue about on rust-lang/rust, during a doc build it should block the `#![feature(extern_prelude)]` check and just leave it as an unresolved path.

**Comment by Nemo157** [comment]
Oh, there's one more at https://github.com/rust-lang-nursery/futures-rs/blob/62827f1776e833a948cb81582988cb7a70a8b700/futures-channel/src/mpsc/mod.rs#L336, it would be great to check if changing both fixes it for `futures-channel` at least to make sure my rationale above is correct.

**Comment by sdroege** [comment]
Oh yes, changing both fixes it

**Comment by sdroege** [comment]
The build failure in the futures crate was just transitive from futures-channel, we're good with this fortunately.

**Pull request merged**
