### PR TITLE
Fix test build and doctests with latest nightly

### PR DESCRIPTION
**Pull request by sdroege**
Fixes https://github.com/rust-lang-nursery/futures-rs/issues/1096

----

This does not fix `futures/testcrate` as that one seems to have quite a few more problems

### CODE REVIEW

**Comment by sdroege** [comment]
It would probably make sense to add the nightly tests to travis. I can add that if you agree

**Comment by MajorBreakfast** [comment]
Feel free to add the nightly tests to the CI. I agree that having them in there is a good idea.

The CI fails because of some changes to `cfg(target_has_atomic)`. Fixing this is super easy, though. More about it here: https://github.com/rust-lang-nursery/futures-rs/pull/1089

**Comment by sdroege** [comment]
Ok, this is all running now. The only thing left is the test-crate, that seems to need some more attention

**Comment by MajorBreakfast** [comment]
And it's green. Wonderful! Thanks :)

**Pull request merged**
