### PR TITLE
Implement Stream for Either

### LINKED ISSUE #614: impl Stream for future::Either
For code that returns one of multiple `Stream`s it'd be nice to have `future::Either` also impl `Stream`.

```rust
fn foo() -> impl Stream {
    let v = match some_result {
        Ok(v) => v,
        Err(err) => return Either::A(stream::once(Err(err))),
    };

    return Either::B(some_stream(v));
}
```

### PR DESCRIPTION
**Pull request by Kixunil**
Closes #614

Cherry-picked from 0.2

### CODE REVIEW

**Comment by cramertj** [comment]
Thanks! Do you need a release?

**Comment by Kixunil** [comment]
That'd be very helpful!

**Comment by cramertj** [comment]
@Kixunil done!

**Comment by Kixunil** [comment]
Thanks a lot!

**Pull request merged**
