### PR TITLE
Stage 0.3.0-alpha.12

### PR DESCRIPTION
**Pull request by cramertj**

### CODE REVIEW

**Comment by Nemo157** [comment]
Idea I had after seeing some issues with pinning the versions of the sub-crates on urlo and discord: should all the internal dependencies be exact version constraints during the alphas? We don't really provide any back-compat between the different alphas so there's little chance of having a mixture of versions working.

**Comment by cramertj** [comment]
You mean should we set `=x.y.z` rather than `x.y.z`? I'd be fine with that.

**Comment by cramertj** [comment]
I've pushed a change that pins the exact versions.

**Comment by Nemo157** [comment]
:+1: Yep, that's what I meant. Changes LGTM.

**Pull request merged**
